# === General zsh config ===

# ====== Options ======
setopt NO_CASE_GLOB
setopt SHARE_HISTORY
setopt EXTENDED_HISTORY
setopt APPEND_HISTORY
setopt HIST_VERIFY
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_DUPS
setopt HIST_FIND_NO_DUPS
setopt HIST_REDUCE_BLANKS
setopt HIST_IGNORE_SPACE
export HISTFILE=~/.zhistory
setopt PROMPT_SUBST
setopt AUTO_PUSHD


# ====== Prompt ======
autoload -Uz vcs_info
precmd_vcs_info() { vcs_info }
precmd_functions+=( precmd_vcs_info )
zstyle ':vcs_info:git:*' formats ' %F{242}[%b]%f'
zstyle ':vcs_info:*' enable git
PROMPT='$(_emoji_prompt_info) %B%F{%(?.blue.red)}%1~%f%b$vcs_info_msg_0_%F{yellow}$(_aws_prompt_info)%F{default} '


_emoji_prompt_info() {
  if [ -z "${HISTFILE:-}" ]; then
    echo "🙈"
  else
    echo "🦄"
  fi
}

_aws_prompt_info() {
  local profile="${AWS_PROFILE:-${AWS_VAULT:-}}"
  if [ -n "$profile" ]; then
    echo " (🔓 $profile)"
  fi
}

# ====== Completion ======
# Colors for directories, ls, cd, etc.
zstyle ':completion:*' list-colors 'di=34:ln=35:so=32:pi=33:ex=31:bd=46;34:cd=43;34:su=41;30:sg=46;30:tw=42;30:ow=43;30' && export CLICOLOR=1
# Case-insensitive completion
zstyle ':completion:*' matcher-list 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]} l:|=* r:|=*' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]} l:|=* r:|=*' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]} l:|=* r:|=*'
# Partial completion suggestions
zstyle ':completion:*' list-suffixes
zstyle ':completion:*' expand prefix suffix
# Completion menu
zstyle ':completion:*' menu select
bindkey '^[[Z' reverse-menu-complete
autoload -U select-word-style
select-word-style bash
# Support bash completions
autoload bashcompinit && bashcompinit
# shell completion for homebrew (https://docs.brew.sh/Shell-Completion)
if type brew &>/dev/null; then
  FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
fi

autoload -Uz compinit && compinit



# ====== Editing ======
bindkey -v
bindkey "^?" backward-delete-char
export EDITOR="nvim"
export KEYTIMEOUT=1
# Block cursor and line cursor for normal and insert mode, respectively
set-cursor() {
  case "$KEYMAP" in
    vicmd) echo -ne '\e[1 q';;
    viins|main) echo -ne '\e[5 q';;
  esac
  zle reset-prompt
}
zle -N zle-line-init set-cursor
zle -N zle-keymap-select set-cursor

# === Aliases ===
alias vim="nvim"
alias tmux="tmux -u"
alias la="ls -la"
alias ll="ls -l"
alias git-root='cd "$(git rev-parse --show-toplevel)"'
alias mkcdtmp='cd "$(mktemp -d)"'
alias incognito=' if [ -n "${HISTFILE_INCOGNITO:-}" ]; then OLD_HISTSIZE="${HISTSIZE:-2000}"; export HISTSIZE=0; export HISTFILE="$HISTFILE_INCOGNITO"; unset HISTFILE_INCOGNITO; export HISTSIZE="$OLD_HISTSIZE"; unset OLD_HISTSIZE; clear; else export HISTFILE_INCOGNITO="${HISTFILE:-}"; unset HISTFILE; fi'


# === Theming ===

# ====== tinted-shell (base16) ======
BASE16_SHELL_PATH="$HOME/.config/tinted-shell"
[ -n "$PS1" ] && [ -s "$BASE16_SHELL_PATH/profile_helper.sh" ] && \
  source "$BASE16_SHELL_PATH/profile_helper.sh"

# Helper function for toggling between light and dark mode
toggle-theme() {
  # Some nice themes:
  # catppuccin-mocha, da-one-sea, horizon-terminal-dark,
  # onedark, snazzy, penumbra-dark-contrast-plus,
  # precious-dark-eleven, precious-dark-fifteen,
  # primer-dark-dimmed
  local current
  current=$(cat "$HOME/.config/tinted-theming/theme_name" 2>/dev/null)
  if [[ $current == horizon-terminal-dark ]]; then
    set_theme selenized-white
  else
    set_theme horizon-terminal-dark
  fi
}

source /opt/homebrew/opt/asdf/libexec/asdf.sh
export ASDF_DATA_DIR="$HOME/.asdf"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

eval "$(direnv hook zsh)"

jwt-decode() {
  python3 -c "import sys,base64,json;print(json.dumps(json.loads(base64.urlsafe_b64decode(sys.stdin.read().split('.')[1]+'==')),indent=2))"
}

urldecode() {
  echo "$1" | python3 -c "import sys; import urllib.parse; print(urllib.parse.unquote(sys.stdin.read()))"
}

_aws_sso_login() {
  local fn_name="$1"
  local sso_session="$2"
  local sso_start_url="$3"
  local admin_profile_confirmation_pattern="$4"
  shift 4
  if [ "$#" -lt 1 ] || [ "$1" = "--help" ]; then
    echo "Usage:" >&2
    echo "  $fn_name <profile-name>                # Starts a shell session with AWS credentials" >&2
    echo "  $fn_name <profile-name> -- <command>   # Runs a single command with AWS credentials" >&2
    echo "  $fn_name --browser <profile-name>      # Opens the AWS Console in your default browser" >&2
    return 1
  fi

  if [ "$1" = "--browser" ]; then
    shift
    if [ "$#" -ne 1 ]; then
      echo "You need to specify exactly one config profile" >&2
      return 1
    fi
    sso_role_name="$(aws configure --profile "$1" get "sso_role_name")"
    sso_account_id="$(aws configure --profile "$1" get "sso_account_id")"
    sso_start_url="$sso_start_url"
    url="$sso_start_url/#/console?account_id=$sso_account_id&role_name=$sso_role_name"
    if command -v xdg-open >/dev/null 2>&1; then
      xdg-open "$url"
    elif command -v open >/dev/null 2>&1; then
      open "$url"
    else
      echo "Failed to open default web browser" >&2
      echo "Visit the following URL to log in: $url"
    fi
    return
  fi

  if [ "$#" -ne 1 ] && [ "${2:-}" != "--" ]; then
    echo "You need to specify exactly one config profile" >&2
    return 1
  elif [ "${2:-}" = "--" ] && [ "$#" -lt 3 ]; then
    echo "You need to specify a command to run" >&2
    return 1
  fi
  if test "$admin_profile_confirmation_pattern" != "" && echo "$1" | tr '[:upper:]' '[:lower:]' | grep -q -- "$admin_profile_confirmation_pattern"; then
    if ! bash -c 'confirm() { local query yn; query="$1"; while true; do read -rp "$query " yn 1>&2; case $yn in yes ) return 0 ;; [nN]* ) return 1 ;; * ) printf "[!] Please answer yes or no.\n" 1>&2;; esac; done; }; confirm "[?] Are you sure you want to use an administrator role in a production environment? [yes/no]?"'; then
      return 0
    fi
  fi
  (
    unset AWS_ACCESS_KEY_ID
    unset AWS_SECRET_ACCESS_KEY
    unset AWS_SESSION_TOKEN
    export AWS_PROFILE="$1"
    if { aws sts get-caller-identity >/dev/null 2>&1 } || { aws sso login && { aws sts get-caller-identity >/dev/null 2>&1 } } || { aws sso logout && { aws sso login && aws sts get-caller-identity >/dev/null 2>&1 } }; then
      if [ "${2:-}" = "--" ]; then
        shift; shift; "$@"
      else
        exec "$SHELL"
      fi
    else
      echo "Failed to login" >&2
      return 1
    fi
  )
}

test -f "$HOME/dotfiles/local/zsh/zshrc.local" && source "$HOME/dotfiles/local/zsh/zshrc.local"
test -f "$HOME/dotfiles/local/zsh/zshrc.work" && source "$HOME/dotfiles/local/zsh/zshrc.work"
